# Generated by Django 6.0.5 on 2026-05-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetClassAttributeMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party_id', models.CharField(max_length=64)),
                ('asset_class_key', models.CharField(max_length=64)),
                ('attr_ref_key', models.CharField(max_length=128)),
                ('attr_name', models.CharField(max_length=255)),
                ('data_type', models.CharField(default='NUMERIC', max_length=32)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('source', models.CharField(default='TEMPLATE', max_length=32)),
                ('upd_by', models.CharField(default='SYSTEM', max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party_id', models.CharField(max_length=64)),
                ('asset_ref_key', models.CharField(max_length=128)),
                ('parent_asset_ref_key', models.CharField(max_length=128)),
                ('is_container', models.CharField(default='Y', max_length=1)),
                ('container_ref_key', models.CharField(max_length=128)),
                ('upd_by', models.CharField(default='SYSTEM', max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party_id', models.CharField(max_length=64)),
                ('site_id', models.CharField(max_length=128)),
                ('equip_name', models.CharField(max_length=128)),
                ('equip_short_name', models.CharField(max_length=128)),
                ('equip_make', models.CharField(blank=True, max_length=128)),
                ('equip_model', models.CharField(blank=True, max_length=128)),
                ('equip_serial_num', models.CharField(blank=True, max_length=128)),
                ('supplier_oem_id', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(default='ACT', max_length=24)),
                ('created_by', models.CharField(default='SYSTEM', max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MqttMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party_id', models.CharField(max_length=64)),
                ('site_ref_key', models.CharField(max_length=128)),
                ('asset_class_key', models.CharField(max_length=64)),
                ('asset_ref_key', models.CharField(max_length=128)),
                ('attr_ref_key', models.CharField(max_length=128)),
                ('attr_data_type', models.CharField(default='NUMERIC', max_length=32)),
                ('mqtt_topic', models.CharField(max_length=512)),
                ('status', models.CharField(default='ACT', max_length=24)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OnboardingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_file', models.FileField(upload_to='onboarding/uploads/')),
                ('output_excel', models.FileField(blank=True, upload_to='onboarding/outputs/')),
                ('output_sql', models.FileField(blank=True, upload_to='onboarding/outputs/')),
                ('output_zip', models.FileField(blank=True, upload_to='onboarding/outputs/')),
                ('party_id', models.CharField(default='SEKURA', max_length=64)),
                ('site_ref_key', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=24)),
                ('error_message', models.TextField(blank=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('party_name', models.CharField(max_length=255)),
                ('status', models.CharField(default='ACT', max_length=24)),
                ('upd_by', models.CharField(default='SYSTEM', max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TelemetryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party_id', models.CharField(max_length=64)),
                ('site_ref_key', models.CharField(max_length=128)),
                ('asset_ref_key', models.CharField(max_length=128)),
                ('asset_class_key', models.CharField(max_length=64)),
                ('telemetry_key', models.CharField(max_length=128)),
                ('source_tag', models.CharField(max_length=255)),
                ('data_type', models.CharField(default='NUMERIC', max_length=32)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(default='ACT', max_length=24)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party_id', models.CharField(max_length=64)),
                ('asset_class_key', models.CharField(max_length=64)),
                ('class_name', models.CharField(max_length=128)),
                ('class_desc', models.TextField(blank=True)),
                ('upd_by', models.CharField(default='SYSTEM', max_length=64)),
            ],
            options={
                'unique_together': {('party_id', 'asset_class_key')},
            },
        ),
        migrations.CreateModel(
            name='AssetMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party_id', models.CharField(max_length=64)),
                ('asset_ref_key', models.CharField(max_length=128)),
                ('asset_class_key', models.CharField(max_length=64)),
                ('asset_name', models.CharField(blank=True, max_length=255)),
                ('source_ref', models.CharField(blank=True, max_length=255)),
                ('upd_by', models.CharField(default='SYSTEM', max_length=64)),
            ],
            options={
                'unique_together': {('party_id', 'asset_ref_key')},
            },
        ),
    ]
