# Generated by Django 6.0.5 on 2026-05-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(db_index=True, max_length=80)),
                ('brand', models.CharField(db_index=True, max_length=80)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('search_blob', models.TextField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['category', 'price'], name='onboarding__categor_950af1_idx'), models.Index(fields=['brand', 'category'], name='onboarding__brand_163eea_idx')],
            },
        ),
    ]
