# Generated by Django 6.0.5 on 2026-05-14 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_product'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='onboarding__categor_950af1_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='onboarding__brand_163eea_idx',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
